version: "3.7"
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "todolist"
      MYSQL_PASSWORD: "admin"
    volumes:
      - ./init.sql:/data/application/init.sql
  node_web:
    build: .
    # command: sh -c "./nodestart.sh"
    depends_on:
      - mysql
    ports:
      - "9999:9999"